# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: header.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "Header" do
    optional :page_size, :int32, 1
    optional :transaction_id, :int32, 2
    optional :free_space_start, :int32, 3
    optional :free_space_end, :int32, 4
  end
end

Header = Google::Protobuf::DescriptorPool.generated_pool.lookup("Header").msgclass
