# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: movie.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "Movie" do
    optional :id, :int32, 1
    optional :year, :int32, 2
    optional :name, :string, 3
  end
end

Movie = Google::Protobuf::DescriptorPool.generated_pool.lookup("Movie").msgclass
