# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rating.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "Rating" do
    optional :id, :int32, 1
    optional :score, :int32, 2
    optional :movie_id, :int32, 3
  end
end

Rating = Google::Protobuf::DescriptorPool.generated_pool.lookup("Rating").msgclass
